apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: sampleapp
          image: claudeglauser/sample-webapp:latest
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.25"
            limits:
              memory: "1000Mi"
              cpu: "1"
          env:
            - name: ConnectionStrings__SampleWebAppContext
              value: "Server=localhost;Port=5432;Database=test;User Id=postgres;Password=verysecret"
            - name: DatabaseTech
              value: "NpgSql"
        - name: postgresql
          image: postgres
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.25"
            limits:
              memory: "1000Mi"
              cpu: "1"
          env:
            - name: POSTGRES_PASSWORD
              value: "verysecret"